# Generated by Django 4.1.13 on 2025-01-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='template_color',
            field=models.CharField(default='#000000', max_length=255, unique=True),
        ),
    ]
