# Generated by Django 4.1.13 on 2025-01-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_setting_template_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
