# Generated by Django 4.1.13 on 2025-01-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_setting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_payment_method',
            field=models.CharField(choices=[('Cash', 'CASH'), ('Cheque', 'CHEQUE'), ('Bank_Transfer', 'BANK_TRANSFER')], default='NONE', max_length=255),
        ),
    ]
